server:
  port: 9093
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: noor1997
    driverClassName: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: PAYMENT-SERVICE
  config:
    import:
    - configserver:http://localhost:9999
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:9090/eureka}
